repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: detect-aws-credentials
        args: [ --allow-missing-credentials ]
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.4
    hooks:
      # Run the Ruff formatter.
      - id: ruff-format
        exclude: research/.+\.py
      # Run the Ruff linter.
      - id: ruff
        exclude: research/.+\.py
