name: Branch Protection

on:
  pull_request:
    branches: [main]

jobs:
  enforce-merge-restrictions:
    runs-on: ubuntu-latest
    steps:
      - name: Check if authorized to merge
        run: |
          # Check repository permissions instead of org membership
          # (default GITHUB_TOKEN doesn't have org:read permissions)

          CURRENT_USER="${{ github.actor }}"
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"

          echo "Repository: $REPO_OWNER/$REPO_NAME"
          echo "Current user: $CURRENT_USER"
          echo "PR author: ${{ github.event.pull_request.user.login }}"
          echo ""

          # Check if user has write access to the repository
          RESPONSE=$(gh api repos/$REPO_OWNER/$REPO_NAME/collaborators/$CURRENT_USER/permission || echo '{"permission": "none"}')
          PERMISSION=$(echo "$RESPONSE" | jq -r '.permission')

          echo "User permission level: $PERMISSION"

          if [[ "$PERMISSION" == "admin" || "$PERMISSION" == "write" || "$PERMISSION" == "maintain" ]]; then
            echo "✅ User $CURRENT_USER has $PERMISSION access to repository"
            echo "✅ Authorized to merge to main branch"
          else
            echo "❌ Error: Only users with write access can merge to main branch"
            echo "Current user $CURRENT_USER has '$PERMISSION' permission"
            echo "Please contact repository administrators for access"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate merge conditions
        run: |
          echo "✅ All merge conditions satisfied"
          echo "✅ Authorized user attempting merge"
          echo "✅ Ready to proceed with merge to main branch"
