name: Build and Test Docker Image

on:
  pull_request:
    branches: [main]

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_REPOSITORY: selentai/selent-mcp

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
            image=moby/buildkit:latest

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}
          tags: |
            type=ref,event=pr
            type=sha,format=short
          labels: |
            org.opencontainers.image.title=Selent MCP
            org.opencontainers.image.description=Dynamic Meraki API (816+ endpoints), Multi-Organization Support, Compliance Auditing & Advanced Tools for Model Context Protocol
            org.opencontainers.image.vendor=Selent AI
            org.opencontainers.image.licenses=MIT

      - name: Build Docker image
        uses: docker/build-push-action@v5
        timeout-minutes: 20
        with:
          context: .
          platforms: linux/amd64  
          push: false
          load: true 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SELENT_API_BASE_URL=https://backend.selent.ai
          cache-from: type=gha
          cache-to: type=gha,mode=max
          shm-size: 2g

      - name: Build Summary
        run: |
          echo "✅ Build completed successfully for PR #${{ github.event.pull_request.number }}"
          echo "✅ Image validated - ready to merge"


