name: Build and Deploy to Docker Hub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_REPOSITORY: selentai/selent-mcp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            org.opencontainers.image.title=Selent MCP
            org.opencontainers.image.vendor=Selent AI
            org.opencontainers.image.licenses=MIT

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SELENT_API_BASE_URL=https://backend.selent.ai
          cache-from: type=gha
          cache-to: type=gha,mode=max
          shm-size: 2g

      - name: Load and test Docker image
        if: github.event_name == 'pull_request'
        run: |
          # Load the built image for testing
          docker pull ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:pr-${{ github.event.pull_request.number }} || true

          # Test the image starts correctly
          timeout 30s docker run -i --rm \
            -e MERAKI_API_KEY=test_key \
            -e SELENT_API_KEY=test_key \
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:pr-${{ github.event.pull_request.number }} &

          sleep 5
          echo "Image test completed successfully"

      - name: Push to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SELENT_API_BASE_URL=https://backend.selent.ai
          cache-from: type=gha
          cache-to: type=gha,mode=max
          shm-size: 2g


