name: Publish to Docker Hub

on:
  push:
    branches: [main]

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_REPOSITORY: selentai/selent-mcp

jobs:
  deploy:
    name: Build and Publish
    runs-on: ubuntu-latest
    environment: Production
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          df -h

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
            image=moby/buildkit:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}
          tags: |
            type=ref,event=branch
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=Selent MCP
            org.opencontainers.image.description=Dynamic Meraki API (816+ endpoints), Multi-Organization Support, Compliance Auditing & Advanced Tools for Model Context Protocol
            org.opencontainers.image.vendor=Selent AI
            org.opencontainers.image.licenses=MIT

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v5
        timeout-minutes: 30
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SELENT_API_BASE_URL=https://backend.selent.ai
          cache-from: type=gha
          cache-to: type=gha,mode=max
          shm-size: 2g

      - name: Test published image
        run: |
          echo "Waiting for image to be available..."
          sleep 10

          echo "Testing latest image..."
          timeout 30s docker run -i --rm \
            -e MERAKI_API_KEY=test_key \
            -e SELENT_API_KEY=test_key \
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:latest &

          sleep 5
          echo "✅ Published image test completed successfully"

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPOSITORY }}
          readme-filepath: ./README.md
          short-description: "Dynamic Meraki API (816+ endpoints), Multi-Org Support, Compliance Auditing for Model Context Protocol"
